# -*- coding: utf-8 -*-
"""sandbox_cfg_finalpython

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONrsozFhZ6JYPy0GVOmha7BUBD4BUtGV
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

pd.set_option('display.max_rows', None)
variable = df = pd.read_excel(r"World_data.xlsx")
variable.head()

result = df.groupby('WHO_Region').agg({'Confirmed': ['mean', 'min', 'max']})
print("Mean, min, and max values of sales in 2018")
print(result)

print(df.nsmallest(3, ['Confirmed']))
print(df.nlargest(3, ['Confirmed']))

correlation = df.corr()
sns.heatmap(correlation, annot=True)
plt.rcParams['figure.figsize'] = [15, 10]

a = df.groupby('WHO_Region').size()
print (a)

df.groupby("WHO_Region")["Active"].count().plot.pie(figsize=(10,10),autopct='%1.1f%%')



sns.boxplot(x="Confirmed", y="WHO_Region", data=df,
            whis=[0, 100], width=.6, palette="vlag")

sns.stripplot(x="Active", y="WHO_Region", data=df,
              size=4, color=".3", linewidth=0)

df_americas = df[df['WHO_Region'] == "Americas"]
df_americas.head()

plt.plot(df_americas.Country, df_americas.Confirmed, label='Confirmed cases per Country in Americas')
plt.legend();
plt.rcParams['figure.figsize'] = [50, 40]
plt.show()

df_wp = df[df['WHO_Region'] == "Western Pacific"]
df_wp.head()

plt.plot(df_wp.Country, df_wp.Confirmed, label='Confirmed cases per Country in Western Pacific')
plt.legend();
plt.rcParams['figure.figsize'] = [20, 20]
plt.show()









